"""Модуль для хранения констант проекта."""

CATEGORY_TITLE_MAX_LENGTH = 100

QUIZ_TITLE_MAX_LENGTH = 200
QUIZ_DESCRIPTION_MAX_LENGTH = 500

QUESTION_TEXT_MAX_LENGTH = 500
QUESTION_DESCRIPTION_MAX_LENGTH = 500
CORRECT_ANSWER_MAX_LENGTH = 255
EXPLANATION_MAX_LENGTH = 250
DIFFICULTY_MAX_LENGTH = 6


PREVIEW_TEXT_LENGTH = 30

MIN_OPTIONS_COUNT = 2
